#!/usr/bin/env python3
"""Print a cross-reference of every cable in a model: designator, endpoints,
colours, gauge.

Generated rather than hand-written so it cannot drift from the model as the
transcription fills in. Regenerate with:

    .venv/bin/python3 tools/cable_index.py > measurements/cable-index.md
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from build import load  # noqa: E402
from wireviz import wv_merge  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
COMMON = ROOT / "models" / "kz305-common.yml"
FACTORY = ROOT / "models" / "kz305-factory.yml"


def endpoints(connections):
    """Map each cable designator to the connectors on either side of it.

    A connection set alternates connector / cable / connector, so a cable's
    neighbours in the list are its endpoints.
    """
    ends = {}
    for conn_set in connections:
        names = [next(iter(item)) if isinstance(item, dict) else item
                 for item in conn_set]
        for i, name in enumerate(names):
            if 0 < i < len(names) - 1:
                ends.setdefault(name, []).append((names[i - 1], names[i + 1]))
    return ends


def main():
    common = COMMON.read_text(encoding="utf-8")
    model = wv_merge.merge([(str(FACTORY), load(FACTORY, common))])
    ends = endpoints(model.get("connections", []))

    print("# Cable index — factory model\n")
    print("Generated by `tools/cable_index.py`. Do not edit by hand.\n")
    print("Electrical identity only. A single designator here may be more than")
    print("one physical segment where an in-sleeve splice intervenes, which is")
    print("why the measurement log keys on physical branch IDs instead.\n")
    print("| Designator | From | To | Colours | Gauge |")
    print("|---|---|---|---|---|")

    for name, spec in sorted(model.get("cables", {}).items()):
        pairs = ends.get(name, [])
        frm = pairs[0][0] if pairs else "—"
        to = pairs[0][1] if pairs else "—"
        colours = ", ".join(spec.get("colors", [])) or "—"
        gauge = spec.get("gauge", "—")
        print(f"| `{name}` | {frm} | {to} | {colours} | {gauge} |")

    print(f"\n{len(model.get('cables', {}))} cables.")


if __name__ == "__main__":
    main()
