#!/usr/bin/env python3
"""Inventory every dated evidence claim in the models and measurement logs,
classified by HOW it was established.

This exists because the project's claims come from sources with very different
demonstrated reliability, and nothing anywhere recorded which claim rests on
which. A design review on 2 Sep 2026 found several claims that had been
withdrawn in one file and left standing in another.

Since the 2 Sep notes cleanup, the model files carry an EXPLICIT evidence tag -
"[meter 29 Aug 2026]", "[bench 2 Sep 2026]", "[OPEN]". Those are read directly.
The regex fallback below still classifies the measurement logs and any note that
predates the convention, and a rising `unstated` count in models/ means the
convention is being skipped.

    .venv/bin/python3 tools/claims_register.py > docs/claims-register.md
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SOURCES = (
    sorted((ROOT / "models").rglob("*.yml"))
    + sorted((ROOT / "measurements").glob("*.md"))
    + sorted((ROOT / "measurements").glob("*.csv"))
)

# Evidence classes, ranked by demonstrated reliability ON THIS PROJECT.
# The ranking is not a prior — it is the observed failure record.
CLASSES = [
    ("meter",   r"\b\d+\.\d+\s*[Oo]hm|rings?\s|continuity|metered|MEASURED|0\.\d\s*Ohm", "meter"),
    ("bench",   r"wire in hand|at the bench|part in hand|with the .* in hand|unsleeved|stamped plate", "bench"),
    ("photo",   r"photograph|pre-teardown|photo\b", "photo"),
    ("scan",    r"600 ?dpi|off the scan|read off the diagram|printed table|the scan", "scan"),
    ("arith",   r"conductor count|arithmetic|count closes|gender complement|by elimination", "arith"),
]

MARKER = re.compile(
    r"(CONFIRMED|MEASURED|WITHDRAWN|OVERTURNED|CORRECTED|IDENTIFIED|CLOSED|RESOLVED|"
    r"SUPERSEDED|ESTABLISHED|TENTATIVE|IN DOUBT|NOT KNOWN|OPEN)\b", re.I)
DATED = re.compile(r"\b(\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\w*\s+20\d\d|20\d\d-\d\d-\d\d)")


# The explicit tag written by the notes convention. Preferred over the regexes
# below, which infer a class from prose and can only ever be a heuristic.
TAG = re.compile(r"\[(meter|bench|photo|scan|arith|inherit)\b", re.I)


def classify(text):
    m = TAG.search(text)
    if m:
        return m.group(1).lower()
    for name, pattern, label in CLASSES:
        if re.search(pattern, text, re.I):
            return label
    return "unstated"


def main():
    rows = []
    for path in SOURCES:
        rel = path.relative_to(ROOT)
        for i, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            m = MARKER.search(line)
            if not m:
                continue
            d = DATED.search(line)
            rows.append({
                "file": str(rel),
                "line": i,
                "marker": m.group(1).upper(),
                "date": d.group(1) if d else "",
                "evidence": classify(line),
                "text": line.strip()[:150],
            })

    by_marker = defaultdict(int)
    by_evidence = defaultdict(int)
    for r in rows:
        by_marker[r["marker"]] += 1
        by_evidence[r["evidence"]] += 1

    print("# Claims register\n")
    print("Generated by `tools/claims_register.py`. Do not edit by hand.\n")
    print("Every dated or status-marked claim in the models and measurement logs,")
    print("classified by **how it was established**. This is a coverage map, not a")
    print("verdict — a line appears here because it carries a marker, not because")
    print("it is wrong.\n")

    print("## Evidence classes, ranked by this project's own failure record\n")
    print("| Class | Demonstrated reliability |")
    print("|---|---|")
    print("| `meter` | **Highest.** No continuity reading has been overturned. |")
    print("| `bench` | High. A wire or part in hand; the base-colour convention exists to keep it that way. |")
    print("| `arith` | High where premises hold — but the premises are the risk. `B06`'s child sum was wrong by one and would have hidden a splice. |")
    print("| `photo` | **Mixed, and under-tested.** One failure and two successes — a sample of three. `docs/kz305-b1-wiring.md` bans colour reads from photographs outright. |")
    print("| `scan` | **Lowest. Twelve failures**, five of them base-versus-tracer. 600 dpi cannot resolve a tracer. |")
    print("| `unstated` | Unknown — the line carries a status marker but names no evidence. |")
    print()
    print("The ranking is the enumerated record in `docs/overturned-claims.md`, not a prior.")
    print("A claim in `models/` classified `unstated` is a note that skipped the evidence-tag")
    print("convention — see `models/factory/00-notes.yml`.\n")

    print("## Counts\n")
    print("| Marker | n |")
    print("|---|---|")
    for k, v in sorted(by_marker.items(), key=lambda x: -x[1]):
        print(f"| {k} | {v} |")
    print()
    print("| Evidence | n |")
    print("|---|---|")
    for k, v in sorted(by_evidence.items(), key=lambda x: -x[1]):
        print(f"| `{k}` | {v} |")
    print()

    live = [r for r in rows if r["marker"] in
            ("CONFIRMED", "MEASURED", "IDENTIFIED", "ESTABLISHED", "CLOSED", "RESOLVED")]
    weak = [r for r in live if r["evidence"] in ("scan", "photo", "unstated")]
    print(f"## ⚠️ Standing claims on the weaker evidence classes — {len(weak)}\n")
    print("These assert something is settled while resting on scan, photograph or")
    print("unstated evidence. **Each needs one confirming test**, or an explicit")
    print("note that it is accepted unverified.\n")
    print("| File | Line | Marker | Evidence | Claim |")
    print("|---|---|---|---|---|")
    for r in sorted(weak, key=lambda r: (r["evidence"], r["file"], r["line"])):
        t = r["text"].replace("|", "\\|")
        print(f"| `{r['file']}` | {r['line']} | {r['marker']} | `{r['evidence']}` | {t} |")
    print()

    unresolved = [r for r in rows if r["marker"] in
                  ("WITHDRAWN", "IN DOUBT", "NOT KNOWN", "TENTATIVE", "OPEN")]
    print(f"## Withdrawn, doubted or open — {len(unresolved)}\n")
    print("| File | Line | Marker | Claim |")
    print("|---|---|---|---|")
    for r in sorted(unresolved, key=lambda r: (r["file"], r["line"])):
        t = r["text"].replace("|", "\\|")
        print(f"| `{r['file']}` | {r['line']} | {r['marker']} | {t} |")
    print(f"\n---\n\n{len(rows)} marked claims across {len(SOURCES)} files.")


if __name__ == "__main__":
    main()
