#!/usr/bin/env python3
"""Print the printed-heat-shrink label schedule for the rebuild harness.

Every wire gets TWO labels, one per end, and each names the FAR end - which
is what you actually want when tracing a wire you have found mid-loom.

Generated rather than hand-written so it cannot drift from the model.

    .venv/bin/python3 tools/label_schedule.py > docs/label-schedule.md

Also writes docs/labels/<size>mm.csv, one file per Rhino cartridge, for
DYMO ID's import on the Rhino 6000+: open a heat-shrink label, Import Data,
pick the file, map the `label` column to the text field, print all. Each row
is one label; the printed text is `label`. The other columns are there so
the row can be checked against the schedule and are not printed.

Cartridge by gauge, from the Dymo fit ranges: 16 AWG on 6 mm, 14 and 12 AWG
on 9 mm, 6 AWG on 19 mm.
"""

import csv

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from build import load  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CSV_DIR = ROOT / "docs" / "labels"
CARTRIDGE_MM = {"16 AWG": 6, "14 AWG": 9, "12 AWG": 9, "6 AWG": 19}
COMMON = ROOT / "models" / "kz305-common.yml"
REBUILD = ROOT / "models" / "kz305-rebuild.yml"

# Label text drops the W_ prefix: every wire has it, so it carries no
# information, and heat shrink on 18 AWG has very little room.
def short(designator):
    return designator[2:] if designator.startswith("W_") else designator


def ends(connections, cables):
    """Yield (cable, near_connector, near_pins, far_connector, far_pins)."""
    for conn_set in connections:
        items = [i for i in conn_set if isinstance(i, dict)]
        for idx, item in enumerate(items):
            name = next(iter(item))
            if name not in cables:
                continue
            left = items[idx - 1] if idx > 0 else None
            right = items[idx + 1] if idx + 1 < len(items) else None
            if not (left and right):
                continue
            ln, lp = next(iter(left.items()))
            rn, rp = next(iter(right.items()))
            yield name, ln, lp, rn, rp


def pinref(connector, pins):
    return f"{connector}-{'/'.join(str(p) for p in pins)}"


def main():
    model = load(REBUILD, COMMON.read_text(encoding="utf-8"))
    # Stock conductors in retained parts are drawn but not cut, so they get
    # no label - see the note above `cables:` in the model (#52).
    everything = model.get("cables", {})
    cables = {k: v for k, v in everything.items()
              if not v.get("ignore_in_bom")
              and "DO NOT BUILD" not in str(v.get("notes") or "")}
    skipped = sorted(k for k, v in everything.items() if v.get("ignore_in_bom"))
    not_built = sorted(k for k, v in everything.items()
                       if "DO NOT BUILD" in str(v.get("notes") or ""))
    rows = []
    for name, ln, lp, rn, rp in ends(model.get("connections", []), cables):
        c = cables[name]
        colour = "/".join(c.get("colors") or ["?"])
        gauge = c.get("gauge", "")
        rows.append((short(name), pinref(ln, lp), pinref(rn, rp), colour, gauge))
        rows.append((short(name), pinref(rn, rp), pinref(ln, lp), colour, gauge))
    rows.sort()

    # CSV per cartridge, for the Rhino 6000+ import.
    CSV_DIR.mkdir(exist_ok=True)
    by_size = {}
    for text, near, far, colour, gauge in rows:
        by_size.setdefault(CARTRIDGE_MM[gauge], []).append(
            (f"{text} >{far}", text, near, far, colour, gauge))
    for size, items in by_size.items():
        with open(CSV_DIR / f"{size}mm.csv", "w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow(["label", "wire", "this_end", "far_end", "colour", "gauge"])
            w.writerows(items)

    print("# Label schedule — rebuild harness\n")
    print("Generated by `tools/label_schedule.py`. Do not edit by hand.\n")
    print("Printed heat-shrink, **two labels per wire**. Each label names the")
    print("**far** end, because that is the question you have when you are")
    print("holding one end of a wire in a loom.\n")
    print("## ⚠️ Label and seal go on BEFORE the terminal is crimped\n")
    print("Heat shrink and the MP280 cavity seal both slide on from the wire")
    print("end. A crimped terminal will not pass either. The order is:\n")
    print("1. Slide on the printed heat-shrink label")
    print("2. Slide on the cavity seal")
    print("3. Strip")
    print("4. Crimp the terminal (conductor **and** seal wings)")
    print("5. Shrink the label\n")
    print("Getting this wrong means cutting the terminal off and starting")
    print("again, one wire at a time, and it is not recoverable any other way.\n")
    print("## Schedule\n")
    print(f"{len(rows)} labels for {len(cables)} wires.\n")
    if skipped:
        print(f"Not labelled: {len(skipped)} conductors that already exist in retained")
        print("stock parts (flagged `ignore_in_bom` in the model): "
              + ", ".join(f"`{short(n)}`" for n in skipped) + ".\n")
    if not_built:
        print("Not labelled because NOT BUILT (marked DO NOT BUILD in the model): "
              + ", ".join(f"`{short(n)}`" for n in not_built) + ".\n")
    counts = {s: len(v) for s, v in sorted(by_size.items())}
    print("**Print files for the Rhino 6000+**, one per cartridge, in `docs/labels/`: "
          + ", ".join(f"`{s}mm.csv` ({n})" for s, n in counts.items())
          + ". DYMO ID: heat-shrink label, Import Data, map `label` to the text field, "
            "print all. Printed text is `NAME >FAR-END`.\n")
    print("| Label text | Goes on end | Reads (far end) | Colour | Gauge |")
    print("|---|---|---|---|---|")
    for text, near, far, colour, gauge in rows:
        print(f"| `{text}` | {near} | `>{far}` | {colour} | {gauge} |")


if __name__ == "__main__":
    main()
