#!/usr/bin/env python3
"""Print the printed-heat-shrink label schedule for the rebuild harness.

Every wire gets TWO labels, one per end, and each names the FAR end - which
is what you actually want when tracing a wire you have found mid-loom.

Generated rather than hand-written so it cannot drift from the model.

    .venv/bin/python3 tools/label_schedule.py > docs/label-schedule.md
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from build import load  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
COMMON = ROOT / "models" / "kz305-common.yml"
REBUILD = ROOT / "models" / "kz305-rebuild.yml"

# Label text drops the W_ prefix: every wire has it, so it carries no
# information, and heat shrink on 18 AWG has very little room.
def short(designator):
    return designator[2:] if designator.startswith("W_") else designator


def ends(connections, cables):
    """Yield (cable, near_connector, near_pins, far_connector, far_pins)."""
    for conn_set in connections:
        items = [i for i in conn_set if isinstance(i, dict)]
        for idx, item in enumerate(items):
            name = next(iter(item))
            if name not in cables:
                continue
            left = items[idx - 1] if idx > 0 else None
            right = items[idx + 1] if idx + 1 < len(items) else None
            if not (left and right):
                continue
            ln, lp = next(iter(left.items()))
            rn, rp = next(iter(right.items()))
            yield name, ln, lp, rn, rp


def pinref(connector, pins):
    return f"{connector}-{'/'.join(str(p) for p in pins)}"


def main():
    model = load(REBUILD, COMMON.read_text(encoding="utf-8"))
    cables = model.get("cables", {})
    rows = []
    for name, ln, lp, rn, rp in ends(model.get("connections", []), cables):
        c = cables[name]
        colour = "/".join(c.get("colors") or ["?"])
        gauge = c.get("gauge", "")
        rows.append((short(name), pinref(ln, lp), pinref(rn, rp), colour, gauge))
        rows.append((short(name), pinref(rn, rp), pinref(ln, lp), colour, gauge))
    rows.sort()

    print("# Label schedule — rebuild harness\n")
    print("Generated by `tools/label_schedule.py`. Do not edit by hand.\n")
    print("Printed heat-shrink, **two labels per wire**. Each label names the")
    print("**far** end, because that is the question you have when you are")
    print("holding one end of a wire in a loom.\n")
    print("## ⚠️ Label and seal go on BEFORE the terminal is crimped\n")
    print("Heat shrink and the MP280 cavity seal both slide on from the wire")
    print("end. A crimped terminal will not pass either. The order is:\n")
    print("1. Slide on the printed heat-shrink label")
    print("2. Slide on the cavity seal")
    print("3. Strip")
    print("4. Crimp the terminal (conductor **and** seal wings)")
    print("5. Shrink the label\n")
    print("Getting this wrong means cutting the terminal off and starting")
    print("again, one wire at a time, and it is not recoverable any other way.\n")
    print("## Schedule\n")
    print(f"{len(rows)} labels for {len(cables)} wires.\n")
    print("| Label text | Goes on end | Reads (far end) | Colour | Gauge |")
    print("|---|---|---|---|---|")
    for text, near, far, colour, gauge in rows:
        print(f"| `{text}` | {near} | `>{far}` | {colour} | {gauge} |")


if __name__ == "__main__":
    main()
