#!/usr/bin/env python3
"""Draw the PDM's fuse side: every cavity, what is in it, and what fuse or
relay sits over it.

    .venv/bin/python3 tools/pdm_map.py > docs/pdm-map.svg

Wires and cavities come from tools/cut_list.py, which reads the model, so
this cannot drift from the cut list. Fuse ratings are the 4 Sep table (#41)
and the spare layout is docs/pdm-cavity-map.md, 11 Sep.

Drawn as you look at the FUSE SIDE, the side you see with the block on the
bike. The part's column numbers run 1-10 from the WIRE side, so from the fuse
side c10 is on the left and c1 on the right. r1 at the top,
cavity = (row-1)*10 + column. There is no keyway; the printed numbers orient it.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import cut_list as cl  # noqa: E402

FUSE_A = {1: 5, 2: 5, 3: 10, 4: 10, 5: 15, 6: 5, 7: 5, 8: 7.5, 9: 10, 10: 7.5, 11: 5}
# spare fuses: (col, top row) -> rating
SPARE_FUSE = {(2, 1): 5, (2, 3): 5, (2, 5): 7.5, (9, 5): 10, (10, 1): 10,
              (10, 3): 7.5, (10, 5): 15}
SPARE_RELAY = ("K_SPARE", 3, 5)  # name, top row, lowest column

# Mini fuse body colours by rating, the standard code.
FUSE_FILL = {5: "#d8a25a", 7.5: "#b98a5e", 10: "#d9534f", 15: "#4a86c8", 20: "#e6d44a"}
WIRE_FILL = {"RD": "#d0342c", "BU": "#2f6fce", "WH": "#f4f4f4", "BK": "#222",
             "GY": "#9a9a9a", "BG": "#c9a26b", "GN": "#2e9e4f", "YE": "#f2d22e"}

CELL = 96
PAD_X, PAD_Y = 70, 110
ROWS, COLS = 6, 10


def short(name):
    return name[2:] if name.startswith("W_") else name


def main():
    common = cl.COMMON.read_text(encoding="utf-8")
    doc = cl.load(cl.REBUILD, common)
    cables = doc["cables"]
    ends = cl.ends(doc)

    # cavity (row, col) -> (wire, colour, gauge)
    occupied = {}
    for name, cable in cables.items():
        cable = cable or {}
        if cable.get("ignore_in_bom") or "DO NOT BUILD" in str(cable.get("notes") or ""):
            continue
        for left, right in ends.get(name, []):
            for node, pins in (left, right):
                cav = cl.cavity_of(node, pins[0]) if node else None
                if not cav:
                    continue
                col = int(cav[1:cav.index(" ")])
                row = int(cav[cav.index("r") + 1:cav.index(" (")])
                occupied[(row, col)] = (short(name), "/".join(cable.get("colors") or []),
                                        cable.get("gauge", ""))

    # fuse positions: PDM_CAVITY names give "(Fn IN)" / "(Fn OUT)"
    fuses = {}  # n -> (col, top row)
    for way, cav in cl.PDM_CAVITY.items():
        n = int(cav[cav.index("(F") + 2:cav.index(" ", cav.index("(F"))])
        col = int(cav[1:cav.index(" ")])
        row = int(cav[cav.index("r") + 1:cav.index(" (")])
        c, r = fuses.get(n, (col, row))
        fuses[n] = (col, min(r, row))
    # the OUT wire names the circuit
    circuit = {}
    for n, (col, top) in fuses.items():
        w = occupied.get((top + 1, col))
        circuit[n] = w[0] if w else ""

    W = PAD_X * 2 + COLS * CELL
    H = PAD_Y + ROWS * CELL + 190
    o = []
    a = o.append
    a(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
      f'font-family="Helvetica, Arial, sans-serif">')
    a(f'<rect width="{W}" height="{H}" fill="#fbfaf7"/>')
    a(f'<text x="{PAD_X}" y="36" font-size="22" font-weight="700" fill="#222">'
      'PDM MTA 0301370 — fuse side, as seen on the bike</text>')
    a(f'<text x="{PAD_X}" y="60" font-size="14" fill="#555">c10 left, c1 right (the numbers '
      'are printed on the wire side), r1 top. cavity = (row − 1) × 10 + column. '
      'Generated by tools/pdm_map.py from the model.</text>')

    def x(col):
        # fuse-side view: c10 at the left
        return PAD_X + (COLS - col) * CELL

    def y(row):
        return PAD_Y + (row - 1) * CELL

    # body
    a(f'<rect x="{PAD_X - 14}" y="{PAD_Y - 6}" width="{COLS * CELL + 28}" '
      f'height="{ROWS * CELL + 12}" rx="10" fill="#e8e6e0" stroke="#999" stroke-width="2"/>')

    # column / row labels
    for c in range(1, COLS + 1):
        a(f'<text x="{x(c) + CELL / 2}" y="{y(ROWS + 1) + 24}" font-size="14" '
          f'fill="#444" text-anchor="middle">c{c}</text>')
    for r in range(1, ROWS + 1):
        a(f'<text x="{PAD_X - 30}" y="{y(r) + CELL / 2 + 5}" font-size="14" '
          f'fill="#444" text-anchor="middle">r{r}</text>')

    # relays, drawn under the cavities so the dots stay visible. A relay
    # covers columns c and c+1; in this view c+1 is the left-hand one.
    relays = [(n, r, c) for n, (r, c) in cl.RELAY_ORIGIN.items()] + [SPARE_RELAY]
    for name, r, c in relays:
        spare = name == "K_SPARE"
        left = x(c + 1)
        a(f'<rect x="{left + 6}" y="{y(r) + 6}" width="{2 * CELL - 12}" height="{2 * CELL - 12}" '
          f'rx="12" fill="{"#f3f1ec" if spare else "#dfe7f3"}" '
          f'stroke="{"#aaa" if spare else "#4a6a99"}" stroke-width="2.5" '
          f'{"stroke-dasharray=\"8 6\"" if spare else ""}/>')
        a(f'<text x="{left + CELL}" y="{y(r) + CELL + 6}" font-size="17" font-weight="700" '
          f'fill="{"#888" if spare else "#2c4a75"}" text-anchor="middle">{name}</text>')
        if spare:
            a(f'<text x="{left + CELL}" y="{y(r) + CELL + 26}" font-size="12" fill="#888" '
              'text-anchor="middle">spare, unwired</text>')
        else:
            for pin, (dr, dc) in cl.RELAY_PIN_OFFSET.items():
                a(f'<text x="{x(c + dc) + CELL / 2}" y="{y(r + dr) + 20}" font-size="12" '
                  f'font-weight="700" fill="#2c4a75" text-anchor="middle">'
                  f'{cl.RELAY_PIN_NAME[pin]}</text>')

    # fuses
    def fuse(col, top, rating, label, spare):
        fill = FUSE_FILL[rating]
        a(f'<rect x="{x(col) + 8}" y="{y(top) + 8}" width="{CELL - 16}" height="{2 * CELL - 16}" '
          f'rx="10" fill="{fill}" fill-opacity="{0.35 if spare else 0.55}" '
          f'stroke="{"#aaa" if spare else "#6b5a3a"}" stroke-width="2" '
          f'{"stroke-dasharray=\"8 6\"" if spare else ""}/>')
        # between the two cavities: above the lower dot, below the upper name
        a(f'<text x="{x(col) + CELL / 2}" y="{y(top) + CELL + 8}" font-size="15" '
          f'font-weight="700" fill="#222" text-anchor="middle">{label}</text>')
        a(f'<text x="{x(col) + CELL / 2}" y="{y(top) + CELL + 26}" font-size="13" '
          f'fill="#333" text-anchor="middle">{rating:g} A</text>')

    for n, (col, top) in sorted(fuses.items()):
        fuse(col, top, FUSE_A[n], f"F{n}", False)
    for (col, top), rating in SPARE_FUSE.items():
        fuse(col, top, rating, "spare", True)

    # cavities
    for r in range(1, ROWS + 1):
        for c in range(1, COLS + 1):
            cx, cy = x(c) + CELL / 2, y(r) + CELL / 2
            w = occupied.get((r, c))
            if w:
                name, colour, gauge = w
                base = colour.split("/")[0]
                a(f'<circle cx="{cx}" cy="{cy + 14}" r="9" fill="{WIRE_FILL.get(base, "#ccc")}" '
                  'stroke="#333" stroke-width="1.2"/>')
                a(f'<text x="{cx}" y="{cy + 38}" font-size="10.5" font-weight="600" fill="#222" '
                  f'text-anchor="middle">{name}</text>')
                if gauge and gauge != "16 AWG":
                    a(f'<text x="{cx}" y="{cy - 2}" font-size="9" fill="#a33" '
                      f'text-anchor="middle">{gauge}</text>')
            else:
                a(f'<circle cx="{cx}" cy="{cy + 14}" r="9" fill="none" stroke="#999" '
                  'stroke-width="1.2" stroke-dasharray="3 2"/>')
                a(f'<text x="{cx}" y="{cy + 38}" font-size="10" fill="#999" '
                  'text-anchor="middle">plug</text>')

    # bands: HOT is c1-c2 (right-hand end in this view), SWITCHED c7-c10 (left)
    by = y(ROWS + 1) + 44
    a(f'<text x="{x(2) + CELL}" y="{by}" font-size="13" font-weight="700" fill="#a33" '
      'text-anchor="middle">HOT — F1 F4 F5</text>')
    a(f'<text x="{x(6) + 2 * CELL}" y="{by}" font-size="13" font-weight="700" fill="#2c4a75" '
      'text-anchor="middle">6 relays</text>')
    a(f'<text x="{x(10) + 2 * CELL}" y="{by}" font-size="13" font-weight="700" fill="#7a5a1e" '
      'text-anchor="middle">SWITCHED — behind K_MAIN 87</text>')

    # circuit key and legend
    ky = by + 30
    keys = [f"F{n} {FUSE_A[n]:g} A → {circuit[n]}" for n in sorted(fuses)]
    a(f'<text x="{PAD_X}" y="{ky}" font-size="12" fill="#333">' + "    ".join(keys[:6]) + '</text>')
    a(f'<text x="{PAD_X}" y="{ky + 18}" font-size="12" fill="#333">' + "    ".join(keys[6:]) + '</text>')
    lx = PAD_X
    ly = ky + 46
    for i, (code, fill) in enumerate(WIRE_FILL.items()):
        a(f'<circle cx="{lx + i * 90 + 8}" cy="{ly}" r="7" fill="{fill}" stroke="#333" stroke-width="1"/>')
        a(f'<text x="{lx + i * 90 + 22}" y="{ly + 4}" font-size="12" fill="#333">{code}</text>')
    a(f'<text x="{lx}" y="{ly + 26}" font-size="12" fill="#555">Solid dot = wired cavity, '
      'labelled with the wire name (W_ dropped). Dashed dot = cavity plug. '
      'Dashed outline = a populated spare with no wires under it.</text>')
    a(f'<text x="{lx}" y="{ly + 44}" font-size="12" fill="#555">Relay pins read 30 / 86 on '
      'the top row and 85 / 87 on the bottom, seen from this side - the diagonal rule. '
      'A -R1 relay works either way round.</text>')
    a('</svg>')
    print("\n".join(o))


if __name__ == "__main__":
    main()
